#
# Module manifest for module 'MASES.NavenPS'
#
# Generated by: MASES s.r.l.
#

@{

RootModule = 'MASES.NavenPS.psm1'

ModuleVersion = '3.9.1'

CompatiblePSEditions = 'Desktop', 'Core'

GUID = '579EB835-AF47-49CD-9D0C-E5A3F13AA176'

Author = 'MASES s.r.l.'

CompanyName = 'MASES s.r.l.'

Copyright = 'Copyright (c) 2024-2025 MASES s.r.l.'

Description = 'Naven (.NET suite for Apache Maven™) PowerShell (aka NavenPS) is a PowerShell Module to use Apache Maven™ and PowerShell side-by-side. With NavenPS it is possible to:
- create and use Apache Maven™ objects from PowerShell: initialize Apache Maven™ object (Java, Scala, Kotlin, ...), execute methods on the object, read data from the object to be used for further PowerShell code 
- send to JVM objects data managed from PowerShell: e.g. data of PowerShell, like an input from command-line or a variable, can be used as an argument for the initialization or execution of a method of a JVM object

More information within the project hosted on GitHub at https://github.com/masesgroup/Naven for further information.'

PowerShellVersion = '5.1'

# PowerShellHostName = ''

# PowerShellHostVersion = ''

# DotNetFrameworkVersion = ''

# CLRVersion = ''

# ProcessorArchitecture = ''

# RequiredModules = @()

# RequiredAssemblies = @()

# ScriptsToProcess = @()

# TypesToProcess = @()

# FormatsToProcess = @()

# NestedModules = @()

FunctionsToExport = @()

CmdletsToExport = @(
    'Start-NavenPS',
    'Start-Launcher'
)

VariablesToExport = '*'

AliasesToExport = @()

# DscResourcesToExport = @()

# ModuleList = @()

# FileList = @()

PrivateData = @{

    PSData = @{

        Tags = @('NavenPS', 'Naven', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'JVM', 'Java', 'Apache_Maven', 'Maven', 'bridge', 'gateway')

        LicenseUri = 'https://github.com/masesgroup/Naven/blob/master/LICENSE'

        ProjectUri = 'https://github.com/masesgroup/Naven'

        IconUri = 'https://raw.githubusercontent.com/masesgroup/Naven/master/src/net/Common/JCOB128x128.png'

        ReleaseNotes = 'https://github.com/masesgroup/Naven/releases'

    }
} 

HelpInfoURI = 'https://naven.masesgroup.com/articles/usagePS.html'

# DefaultCommandPrefix = ''
}

